spring.application.name=managementapis

spring.datasource.url=jdbc:postgresql://localhost:5432/management_db
spring.jpa.properties.hibernate.default_schema=meu_esquema
spring.datasource.username=usuario
spring.datasource.password=senha
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
